//require('./1.spec');
//require('./2.spec');
//require('./3.spec');
//require('./4.spec')
//require('./5.spec')
//require('./6.spec')
//require('./7.spec')
//require('./8.spec')
//require('./9.spec')
//require('./10.spec')
//require('./11.spec')
require('./12.spec')